// 初始模板/galgame-interface-design/components/dialog-box.tsx
"use client"

import type React from "react"

import { ChevronLeft, ChevronRight } from "lucide-react"
import { useState, useEffect } from "react"

export interface BoxShapePreset {
  id: string
  name: string
  borderRadius: string
  borderWidth: string
  shadow: string
}

export interface NameShapePreset {
  id: string
  name: string
  borderRadius: string
  style: "tag" | "pill" | "square" | "underline" | "floating"
}

export interface ArrowShapePreset {
  id: string
  name: string
  type: "circle" | "square" | "pill" | "minimal" | "inner-round" | "inner-square"
  isInner: boolean
}

export interface IndicatorShapePreset {
  id: string
  name: string
  type: "dots" | "diamonds" | "pulse" | "arrow" | "none"
}

export interface BackgroundPatternPreset {
  id: string
  name: string
  pattern: string
}

export const backgroundPatternPresets: BackgroundPatternPreset[] = [
  { id: "none", name: "无", pattern: "" },
  {
    id: "grid",
    name: "方格",
    pattern:
      "linear-gradient(to right, VAR_BORDER_COLOR 1px, transparent 1px), linear-gradient(to bottom, VAR_BORDER_COLOR 1px, transparent 1px)",
  },
  { id: "dots", name: "圆点", pattern: "radial-gradient(circle, VAR_BORDER_COLOR 1px, transparent 1px)" },
  {
    id: "diamonds",
    name: "菱形",
    pattern:
      "linear-gradient(45deg, VAR_BORDER_COLOR 25%, transparent 25%), linear-gradient(-45deg, VAR_BORDER_COLOR 25%, transparent 25%), linear-gradient(45deg, transparent 75%, VAR_BORDER_COLOR 75%), linear-gradient(-45deg, transparent 75%, VAR_BORDER_COLOR 75%)",
  },
  {
    id: "stripes",
    name: "条纹",
    pattern:
      "repeating-linear-gradient(45deg, transparent, transparent 10px, VAR_BORDER_COLOR 10px, VAR_BORDER_COLOR 20px)",
  },
  {
    id: "gradient-soft",
    name: "柔光渐变",
    pattern: "linear-gradient(135deg, rgba(255,255,255,0.15) 0%, transparent 50%, VAR_BORDER_COLOR 100%)",
  },
]

// 形状预设
export const boxShapePresets: BoxShapePreset[] = [
  { id: "rounded", name: "圆角", borderRadius: "12px", borderWidth: "1px", shadow: "0 4px 20px rgba(0,0,0,0.08)" },
  { id: "pill", name: "胶囊", borderRadius: "24px", borderWidth: "1px", shadow: "0 4px 24px rgba(0,0,0,0.1)" },
  { id: "sharp", name: "直角", borderRadius: "0px", borderWidth: "2px", shadow: "4px 4px 0 rgba(0,0,0,0.1)" },
  { id: "soft", name: "柔和", borderRadius: "16px", borderWidth: "0px", shadow: "0 8px 32px rgba(0,0,0,0.12)" },
  { id: "frame", name: "画框", borderRadius: "4px", borderWidth: "3px", shadow: "inset 0 0 0 1px rgba(0,0,0,0.05)" },
]

export const borderWidthPresets = [
  { id: "none", name: "无", width: "0px" },
  { id: "thin", name: "细", width: "1px" },
  { id: "medium", name: "中", width: "2px" },
  { id: "thick", name: "粗", width: "3px" },
  { id: "bold", name: "加粗", width: "4px" },
]

export const nameShapePresets: NameShapePreset[] = [
  { id: "tag", name: "标签", borderRadius: "6px 6px 0 0", style: "tag" },
  { id: "pill", name: "胶囊", borderRadius: "999px", style: "pill" },
  { id: "square", name: "方形", borderRadius: "0px", style: "square" },
  { id: "underline", name: "下划线", borderRadius: "0px", style: "underline" },
  { id: "floating", name: "悬浮", borderRadius: "8px", style: "floating" },
]

export const arrowShapePresets: ArrowShapePreset[] = [
  { id: "circle", name: "圆形", type: "circle", isInner: false },
  { id: "square", name: "方形", type: "square", isInner: false },
  { id: "pill", name: "胶囊", type: "pill", isInner: false },
  { id: "minimal", name: "极简", type: "minimal", isInner: false },
  { id: "inner-round", name: "内嵌圆", type: "inner-round", isInner: true },
  { id: "inner-square", name: "内嵌方", type: "inner-square", isInner: true },
]

export const indicatorShapePresets: IndicatorShapePreset[] = [
  { id: "dots", name: "呼吸点", type: "dots" },
  { id: "diamonds", name: "菱形", type: "diamonds" },
  { id: "pulse", name: "脉冲", type: "pulse" },
  { id: "arrow", name: "箭头", type: "arrow" },
  { id: "none", name: "无", type: "none" },
]

export interface DialogBoxStyle {
  boxShape: string
  nameShape: string
  arrowShape: string
  indicatorShape: string
  backgroundPattern: string
  borderWidth: string
  colors: {
    boxBackground: string
    boxBorder: string
    nameBackground: string
    nameText: string
    nameBorder: string
    dialogText: string
    narrationText: string
    arrowBackground: string
    arrowIcon: string
    indicatorColor: string
  }
  fontSize: string
}

export const defaultDialogStyle: DialogBoxStyle = {
  boxShape: "rounded",
  nameShape: "tag",
  arrowShape: "circle",
  indicatorShape: "dots",
  backgroundPattern: "none",
  borderWidth: "thin",
  colors: {
    boxBackground: "rgba(255, 255, 255, 0.9)",
    boxBorder: "rgba(16, 185, 129, 0.3)",
    nameBackground: "rgba(236, 253, 245, 0.9)",
    nameText: "#059669",
    nameBorder: "rgba(16, 185, 129, 0.3)",
    dialogText: "#374151",
    narrationText: "#6b7280",
    arrowBackground: "rgba(255, 255, 255, 0.85)",
    arrowIcon: "#10b981",
    indicatorColor: "#10b981",
  },
  fontSize: "16px",
}

export interface ChoiceOption {
  id: string
  text: string
  onClick?: () => void
}

interface ChoiceBoxProps {
  options: ChoiceOption[]
  customStyle?: DialogBoxStyle
  onSelect: (id: string) => void
}

export function ChoiceBox({ options, customStyle, onSelect }: ChoiceBoxProps) {
  const style = customStyle || defaultDialogStyle
  const boxShape = boxShapePresets.find((p) => p.id === style.boxShape) || boxShapePresets[0]
  const borderWidthPreset = borderWidthPresets.find((p) => p.id === style.borderWidth) || borderWidthPresets[1]
  const bgPattern = backgroundPatternPresets.find((p) => p.id === style.backgroundPattern)

  const getBackgroundStyles = () => {
    const styles: React.CSSProperties = {
      backgroundColor: style.colors.boxBackground,
    }
    if (bgPattern?.pattern) {
      const resolvedPattern = resolvePatternWithColor(bgPattern.pattern, style.colors.boxBorder)
      styles.backgroundImage = resolvedPattern
      styles.backgroundSize =
        bgPattern.id === "grid"
          ? "20px 20px"
          : bgPattern.id === "dots"
            ? "10px 10px"
            : bgPattern.id === "diamonds"
              ? "20px 20px"
              : undefined
    }
    return styles
  }

  return (
    <div className="absolute inset-0 z-25 flex items-center justify-center bg-black/30 backdrop-blur-sm">
      <div className="flex flex-col gap-3 w-full max-w-md px-6">
        {options.map((option, index) => (
          <button
            key={option.id}
            onClick={() => onSelect(option.id)}
            className="group relative px-6 py-4 backdrop-blur-md transition-all duration-300 
                       hover:scale-[1.02] hover:shadow-xl active:scale-[0.98]
                       animate-in fade-in slide-in-from-bottom-2"
            style={{
              ...getBackgroundStyles(),
              borderWidth: borderWidthPreset.width,
              borderStyle: "solid",
              borderColor: style.colors.boxBorder,
              borderRadius: boxShape.borderRadius,
              boxShadow: boxShape.shadow,
              animationDelay: `${index * 100}ms`,
              animationFillMode: "backwards",
            }}
          >
            {/* Hover overlay */}
            <div
              className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300"
              style={{
                background: `linear-gradient(90deg, ${style.colors.nameBackground}, transparent)`,
                borderRadius: boxShape.borderRadius,
              }}
            />
            <span className="relative z-10 text-base font-medium" style={{ color: style.colors.dialogText }}>
              {option.text}
            </span>
          </button>
        ))}
      </div>
    </div>
  )
}

interface DialogBoxProps {
  character: string
  text: string
  isLastDialogue: boolean
  isFirstDialogue: boolean
  onPrev: () => void
  onNext: () => void
  dialogKey: number
  customStyle?: DialogBoxStyle
}

function getBorderColorForPattern(borderColor: string, opacity = 0.08): string {
  // 解析 rgba/rgb/hex 颜色
  if (borderColor.startsWith("rgba")) {
    const match = borderColor.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/)
    if (match) {
      return `rgba(${match[1]}, ${match[2]}, ${match[3]}, ${opacity})`
    }
  } else if (borderColor.startsWith("rgb")) {
    const match = borderColor.match(/rgb$$(\d+),\s*(\d+),\s*(\d+)$$/)
    if (match) {
      return `rgba(${match[1]}, ${match[2]}, ${match[3]}, ${opacity})`
    }
  } else if (borderColor.startsWith("#")) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})/i.exec(borderColor)
    if (result) {
      const r = Number.parseInt(result[1], 16)
      const g = Number.parseInt(result[2], 16)
      const b = Number.parseInt(result[3], 16)
      return `rgba(${r}, ${g}, ${b}, ${opacity})`
    }
  }
  return `rgba(0, 0, 0, ${opacity})`
}

function resolvePatternWithColor(pattern: string, borderColor: string): string {
  if (!pattern) return ""
  const patternBorderColor = getBorderColorForPattern(borderColor, 0.08)
  return pattern.replace(/VAR_BORDER_COLOR/g, patternBorderColor)
}

export default function DialogBox({
  character,
  text,
  isLastDialogue,
  isFirstDialogue,
  onPrev,
  onNext,
  dialogKey,
  customStyle,
}: DialogBoxProps) {
  const [displayedText, setDisplayedText] = useState("")
  const [isTyping, setIsTyping] = useState(true)

  const style = customStyle || defaultDialogStyle
  const boxShape = boxShapePresets.find((p) => p.id === style.boxShape) || boxShapePresets[0]
  const nameShape = nameShapePresets.find((p) => p.id === style.nameShape) || nameShapePresets[0]
  const arrowShape = arrowShapePresets.find((p) => p.id === style.arrowShape) || arrowShapePresets[0]
  const indicatorShape = indicatorShapePresets.find((p) => p.id === style.indicatorShape) || indicatorShapePresets[0]
  const bgPattern = backgroundPatternPresets.find((p) => p.id === style.backgroundPattern)
  const borderWidthPreset = borderWidthPresets.find((p) => p.id === style.borderWidth) || borderWidthPresets[1]

  const isPillShape = style.boxShape === "pill"

  const getBoxBackgroundStyles = (): React.CSSProperties => {
    const styles: React.CSSProperties = {
      // 胶囊形状使用更高透明度的背景
      backgroundColor: isPillShape
        ? style.colors.boxBackground.replace(/[\d.]+\)$/, "0.7)")
        : style.colors.boxBackground,
    }
    if (bgPattern?.pattern) {
      const resolvedPattern = resolvePatternWithColor(bgPattern.pattern, style.colors.boxBorder)
      styles.backgroundImage = resolvedPattern
      styles.backgroundSize =
        bgPattern.id === "grid"
          ? "20px 20px"
          : bgPattern.id === "dots"
            ? "10px 10px"
            : bgPattern.id === "diamonds"
              ? "20px 20px"
              : undefined
    }
    return styles
  }

  useEffect(() => {
    setDisplayedText("")
    setIsTyping(true)
    let index = 0
    const timer = setInterval(() => {
      if (index < text.length) {
        setDisplayedText(text.slice(0, index + 1))
        index++
      } else {
        setIsTyping(false)
        clearInterval(timer)
      }
    }, 50)
    return () => clearInterval(timer)
  }, [text, dialogKey])

  const isNarration = !character || character.trim() === ""

  const renderOuterArrowButton = (direction: "left" | "right", disabled: boolean, onClick: () => void) => {
    const { type } = arrowShape
    const { arrowBackground, arrowIcon } = style.colors

    const baseClass = `flex-shrink-0 flex items-center justify-center transition-all duration-200 ${
      disabled ? "opacity-30 cursor-not-allowed" : "active:scale-95 hover:scale-105"
    }`

    const shapeClass = {
      circle: "w-10 h-10 md:w-11 md:h-11 rounded-full",
      square: "w-10 h-10 md:w-11 md:h-11 rounded-lg",
      pill: "w-12 h-9 md:w-14 md:h-10 rounded-full",
      minimal: "w-10 h-10 md:w-11 md:h-11",
      "inner-round": "",
      "inner-square": "",
    }[type]

    const isMinimal = type === "minimal"

    return (
      <button
        onClick={(e) => {
          e.stopPropagation()
          onClick()
        }}
        disabled={disabled}
        className={`${baseClass} ${shapeClass} ${isMinimal ? "" : "backdrop-blur-sm"}`}
        style={{ background: isMinimal ? "transparent" : arrowBackground, color: arrowIcon }}
        aria-label={direction === "left" ? "上一条对话" : "下一条对话"}
      >
        <ChevronLeft className={`w-5 h-5 ${direction === "right" ? "hidden" : ""}`} />
        <ChevronRight className={`w-5 h-5 ${direction === "left" ? "hidden" : ""}`} />
      </button>
    )
  }

  const renderInnerArrowButton = (direction: "left" | "right", disabled: boolean, onClick: () => void) => {
    const { type } = arrowShape
    const { arrowBackground, arrowIcon } = style.colors

    const isRound = type === "inner-round"
    const baseClass = `flex items-center justify-center transition-all duration-200 ${
      disabled ? "opacity-30 cursor-not-allowed" : "active:scale-95 hover:bg-opacity-100"
    }`
    const shapeClass = isRound ? "w-9 h-full rounded-full mx-1" : "w-10 h-full"

    return (
      <button
        onClick={(e) => {
          e.stopPropagation()
          onClick()
        }}
        disabled={disabled}
        className={`${baseClass} ${shapeClass}`}
        style={{
          background: isRound ? arrowBackground : "transparent",
          color: arrowIcon,
          borderLeft: !isRound && direction === "right" ? `1px solid ${style.colors.boxBorder}` : undefined,
          borderRight: !isRound && direction === "left" ? `1px solid ${style.colors.boxBorder}` : undefined,
        }}
        aria-label={direction === "left" ? "上一条对话" : "下一条对话"}
      >
        <ChevronLeft className={`w-5 h-5 ${direction === "right" ? "hidden" : ""}`} />
        <ChevronRight className={`w-5 h-5 ${direction === "left" ? "hidden" : ""}`} />
      </button>
    )
  }

  const renderCharacterName = () => {
    if (isNarration) return null

    const { nameBackground, nameText, nameBorder } = style.colors
    const { style: nameStyleType, borderRadius } = nameShape

    if (nameStyleType === "underline") {
      return (
        <span
          className="inline-block px-1 pb-1 text-sm font-medium"
          style={{
            color: nameText,
            borderBottomWidth: "2px",
            borderBottomStyle: "solid",
            borderBottomColor: nameBorder,
          }}
        >
          {character}
        </span>
      )
    }

    if (nameStyleType === "floating") {
      return (
        <span
          className="inline-block px-3 py-1 text-sm font-medium shadow-md -translate-y-1"
          style={{ background: nameBackground, color: nameText, borderRadius }}
        >
          {character}
        </span>
      )
    }

    const borderStyle =
      nameStyleType === "tag"
        ? {
            borderTopWidth: "1px",
            borderTopStyle: "solid" as const,
            borderTopColor: nameBorder,
            borderLeftWidth: "1px",
            borderLeftStyle: "solid" as const,
            borderLeftColor: nameBorder,
            borderRightWidth: "1px",
            borderRightStyle: "solid" as const,
            borderRightColor: nameBorder,
            borderBottomWidth: "0px",
          }
        : nameStyleType !== "pill"
          ? {
              borderWidth: "1px",
              borderStyle: "solid" as const,
              borderColor: nameBorder,
            }
          : {}

    return (
      <span
        className="inline-block px-3 py-0.5 text-sm font-medium my-0.5"
        style={{
          background: nameBackground,
          color: nameText,
          ...borderStyle,
          borderRadius,
        }}
      >
        {character}
      </span>
    )
  }

  const renderIndicator = () => {
    const { type } = indicatorShape
    const { indicatorColor } = style.colors

    if (type === "none") return null

    if (type === "dots") {
      return (
        <div className="flex gap-1 items-center">
          {[0, 1, 2].map((i) => (
            <span
              key={i}
              className="w-1.5 h-1.5 rounded-full transition-opacity duration-500"
              style={{
                background: indicatorColor,
                opacity: isTyping ? (i === 2 ? 1 : 0.4) : 0.6,
                animation: isTyping && i === 2 ? "pulse 1s ease-in-out infinite" : undefined,
              }}
            />
          ))}
        </div>
      )
    }

    if (type === "diamonds") {
      return (
        <div className="flex gap-1 items-center">
          {[0, 1, 2].map((i) => (
            <span
              key={i}
              className="w-2 h-2 transition-all duration-300"
              style={{
                background: indicatorColor,
                opacity: isTyping ? (i === 2 ? 1 : 0.3 + i * 0.15) : 0.5,
                transform: `rotate(45deg) scale(${isTyping && i === 2 ? 1.1 : 0.9})`,
                animation: isTyping && i === 2 ? "diamondPulse 1.2s ease-in-out infinite" : undefined,
              }}
            />
          ))}
          <style jsx>{`
            @keyframes diamondPulse {
              0%, 100% { opacity: 1; transform: rotate(45deg) scale(1); }
              50% { opacity: 0.6; transform: rotate(45deg) scale(0.8); }
            }
          `}</style>
        </div>
      )
    }

    if (type === "pulse") {
      return (
        <div className="relative w-3 h-3">
          <span
            className="absolute inset-0 rounded-full"
            style={{
              background: indicatorColor,
              opacity: 0.4,
              animation: isTyping ? "ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite" : undefined,
            }}
          />
          <span
            className="absolute inset-0 rounded-full"
            style={{
              background: indicatorColor,
              animation: isTyping ? "pulse 2s ease-in-out infinite" : undefined,
            }}
          />
          <style jsx>{`
            @keyframes ping {
              75%, 100% { transform: scale(2); opacity: 0; }
            }
          `}</style>
        </div>
      )
    }

    if (type === "arrow") {
      return (
        <ChevronRight
          className="w-4 h-4 transition-transform duration-300"
          style={{
            color: indicatorColor,
            animation: isTyping ? "arrowBounce 0.8s ease-in-out infinite" : undefined,
          }}
        />
      )
    }

    return null
  }

  const isInnerArrow = arrowShape.isInner

  return (
    <div className="absolute bottom-0 left-0 right-0 z-20 p-3 md:p-5">
      <div className="max-w-4xl mx-auto flex items-center gap-3">
        {/* 外置左箭头 */}
        {!isInnerArrow && renderOuterArrowButton("left", isFirstDialogue, onPrev)}

        <div
          className={`flex-1 min-h-[110px] md:min-h-[130px] relative flex ${isInnerArrow ? "overflow-hidden" : ""} ${isPillShape ? "backdrop-blur-md" : "backdrop-blur-md"}`}
          style={{
            ...getBoxBackgroundStyles(),
            borderWidth: borderWidthPreset.width,
            borderStyle: "solid",
            borderColor: style.colors.boxBorder,
            borderRadius: boxShape.borderRadius,
            boxShadow: boxShape.shadow,
          }}
        >
          {/* 内置左箭头 */}
          {isInnerArrow && (
            <div className="flex items-center">{renderInnerArrowButton("left", isFirstDialogue, onPrev)}</div>
          )}

          {/* 主内容区 */}
          <div className="flex-1 flex flex-col">
            {/* 角色名区域 */}
            <div className="h-[36px] flex items-end px-5">{renderCharacterName()}</div>

            {/* 对话内容 */}
            <div className="px-5 pb-4 pt-1 flex-1">
              <p
                className={`leading-relaxed tracking-wide ${isNarration ? "italic text-center py-2" : ""}`}
                style={{
                  color: isNarration ? style.colors.narrationText : style.colors.dialogText,
                  fontSize: style.fontSize,
                }}
              >
                {displayedText}
                {isTyping && (
                  <span className="animate-pulse ml-0.5" style={{ color: style.colors.nameText }}>
                    ｜
                  </span>
                )}
              </p>
            </div>

            {/* 呼吸指示器 */}
            <div className="absolute bottom-3 right-4">{!isInnerArrow && renderIndicator()}</div>
            {isInnerArrow && <div className="absolute bottom-3 left-1/2 -translate-x-1/2">{renderIndicator()}</div>}
          </div>

          {/* 内置右箭头 */}
          {isInnerArrow && (
            <div className="flex items-center">{renderInnerArrowButton("right", isLastDialogue, onNext)}</div>
          )}
        </div>

        {/* 外置右箭头 */}
        {!isInnerArrow && renderOuterArrowButton("right", isLastDialogue, onNext)}
      </div>

      {/* 全局动画样式 */}
      <style jsx global>{`
        @keyframes arrowBounce {
          0%, 100% { transform: translateX(0); }
          50% { transform: translateX(3px); }
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
      `}</style>
    </div>
  )
}

// src/live2d与galgame界面前端/components/DialogBox.vue
<template>
  <div class="absolute bottom-0 left-0 right-0 z-20 px-4 md:px-8 pb-4 md:pb-6">
    <div class="flex items-center gap-2 md:gap-4 max-w-4xl mx-auto">
      <!-- 外置左箭头 -->
      <button
        v-if="!isInnerArrow"
        :disabled="isFirstDialogue"
        :class="[
          'flex flex-shrink-0 items-center justify-center transition-all duration-200',
          isFirstDialogue ? 'cursor-not-allowed opacity-40' : 'hover:scale-105',
        ]"
        :style="outerArrowStyle"
        aria-label="上一条对话"
        @click.stop="handlePrev"
      >
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
        </svg>
      </button>

      <!-- 对话框主体 -->
      <div class="flex-1 relative p-4 md:p-5 min-h-[120px]" :style="boxStyle">
        <!-- 内置左箭头 -->
        <div v-if="isInnerArrow" class="absolute left-2 top-1/2 -translate-y-1/2 z-10">
          <button
            :disabled="isFirstDialogue"
            :class="[
              'flex items-center justify-center transition-all duration-200',
              isFirstDialogue ? 'cursor-not-allowed opacity-40' : 'hover:bg-opacity-100',
            ]"
            :style="innerLeftArrowStyle"
            aria-label="上一条对话"
            @click.stop="handlePrev"
          >
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
          </button>
        </div>

          <!-- 角色名区域 -->
        <div
          class="h-6 mb-2 flex items-start"
          :style="{
            paddingLeft: isInnerArrow ? '48px' : 0,
            paddingRight: isInnerArrow ? '48px' : 0,
          }"
        >
          <div
            v-if="!isNarration"
            class="px-3 py-1 text-sm font-medium"
            :style="{
              backgroundColor: dialogStyle.colors.nameBackground,
              color: dialogStyle.colors.nameText,
              borderRadius: nameShape.borderRadius,
              borderBottom: nameShape.style === 'underline' ? `2px solid ${dialogStyle.colors.nameText}` : undefined,
              boxShadow: nameShape.style === 'floating' ? '0 2px 8px rgba(0,0,0,0.1)' : undefined,
            }"
          >
            {{ character }}
          </div>
          <!-- 编辑/删除按钮（仅user消息显示） -->
          <div v-if="props.isEditable && props.messageId !== undefined" class="ml-auto flex gap-2">
            <button
              @click.stop="handleEdit"
              class="p-1 rounded transition-colors hover:bg-black/10"
              aria-label="编辑"
              title="编辑消息"
            >
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                />
              </svg>
            </button>
            <button
              @click.stop="handleDelete"
              class="p-1 rounded transition-colors hover:bg-red-500/20"
              aria-label="删除"
              title="删除消息"
            >
              <svg class="h-4 w-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                />
              </svg>
            </button>
          </div>
          </div>

        <!-- 文字内容 -->
        <div
          :class="['leading-relaxed', isNarration ? 'italic text-center' : '']"
              :style="{
            color: props.isThrough
              ? '#9ca3af'
              : isNarration
                ? dialogStyle.colors.narrationText
                : dialogStyle.colors.dialogText,
            fontSize: `${dialogStyle.fontSize}px`,
            paddingLeft: isInnerArrow ? '48px' : 0,
            paddingRight: isInnerArrow ? '48px' : 0,
              }"
            >
              {{ displayedText }}
          <span v-if="isTyping" class="animate-pulse ml-0.5">|</span>
          </div>

          <!-- 呼吸指示器 -->
        <div class="absolute bottom-3 right-4">
            <component :is="indicatorComponent" />
        </div>

        <!-- 内置右箭头 -->
        <div v-if="isInnerArrow" class="absolute right-2 top-1/2 -translate-y-1/2 z-10">
          <button
            :disabled="isLastDialogue"
            :class="[
              'flex items-center justify-center transition-all duration-200',
              isLastDialogue ? 'cursor-not-allowed opacity-40' : 'hover:bg-opacity-100',
            ]"
            :style="innerRightArrowStyle"
            aria-label="下一条对话"
            @click.stop="handleNext"
          >
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </div>
      </div>

      <!-- 外置右箭头 -->
      <button
        v-if="!isInnerArrow"
        :disabled="isLastDialogue"
        :class="[
          'flex flex-shrink-0 items-center justify-center transition-all duration-200',
          isLastDialogue ? 'cursor-not-allowed opacity-40' : 'hover:scale-105',
        ]"
        :style="outerArrowStyle"
        aria-label="下一条对话"
        @click.stop="handleNext"
      >
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </button>
    </div>
  </div>

  <!-- 编辑对话框 -->
  <div
    v-if="showEditDialog"
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
    @click="cancelEdit"
  >
    <div
      class="bg-card rounded-lg p-6 shadow-xl max-w-md w-full mx-4"
      @click.stop
      :style="{
        backgroundColor: dialogStyle.colors.boxBackground,
        borderColor: dialogStyle.colors.boxBorder,
        borderWidth: '1px',
        borderStyle: 'solid',
      }"
    >
      <h3 class="text-lg font-semibold mb-4" :style="{ color: dialogStyle.colors.dialogText }">编辑消息</h3>
      <textarea
        v-model="editText"
        class="w-full p-3 rounded border resize-none focus:outline-none focus:ring-2"
        :style="{
          backgroundColor: dialogStyle.colors.boxBackground,
          borderColor: dialogStyle.colors.boxBorder,
          color: dialogStyle.colors.dialogText,
        }"
        rows="4"
        placeholder="输入消息内容..."
      ></textarea>
      <div class="flex gap-3 mt-4 justify-end">
        <button
          @click="cancelEdit"
          class="px-4 py-2 rounded transition-colors"
          :style="{
            backgroundColor: dialogStyle.colors.boxBorder + '40',
            color: dialogStyle.colors.dialogText,
          }"
        >
          取消
        </button>
        <button
          @click="confirmEdit"
          class="px-4 py-2 rounded transition-colors"
          :style="{
            backgroundColor: dialogStyle.colors.nameBackground,
            color: dialogStyle.colors.nameText,
          }"
        >
          确认
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, h, onMounted, onUnmounted, ref, VNode, watch } from 'vue';
import {
  type DialogBoxStyle,
  arrowShapePresets,
  backgroundPatternPresets,
  borderWidthPresets,
  boxShapePresets,
  defaultDialogStyle,
  indicatorShapePresets,
  nameShapePresets,
} from '../types/galgame';

interface Props {
  character: string;
  text: string;
  isLastDialogue: boolean;
  isFirstDialogue: boolean;
  onPrev: () => void;
  onNext: () => void;
  dialogKey: number;
  customStyle?: DialogBoxStyle;
  isLoading?: boolean;
  streamingText?: string;
  isThrough?: boolean;
  isEditable?: boolean;
  messageId?: number;
  onEdit?: (messageId: number, newText: string) => void;
  onDelete?: (messageId: number) => void;
}

const props = defineProps<Props>();

const displayedText = ref('');
const isTyping = ref(true);
let typingTimer: ReturnType<typeof setInterval> | null = null;

const TYPING_SPEED = 50;

const dialogStyle = computed(() => props.customStyle || defaultDialogStyle);
const boxShape = computed(() => boxShapePresets.find(p => p.id === dialogStyle.value.boxShape) || boxShapePresets[0]);
const nameShape = computed(
  () => nameShapePresets.find(p => p.id === dialogStyle.value.nameShape) || nameShapePresets[0],
);
const arrowShape = computed(
  () => arrowShapePresets.find(p => p.id === dialogStyle.value.arrowShape) || arrowShapePresets[0],
);
const indicatorShape = computed(
  () => indicatorShapePresets.find(p => p.id === dialogStyle.value.indicatorShape) || indicatorShapePresets[0],
);
const borderWidth = computed(
  () => borderWidthPresets.find(p => p.id === dialogStyle.value.borderWidth) || borderWidthPresets[1],
);
const bgPattern = computed(() => backgroundPatternPresets.find(p => p.id === dialogStyle.value.backgroundPattern));

const isNarration = computed(() => !props.character || props.character.trim() === '');
const isInnerArrow = computed(() => arrowShape.value.isInner);
const isMinimalArrow = computed(() => arrowShape.value.type === 'minimal');
const isPillShape = computed(() => dialogStyle.value.boxShape === 'pill');

// 背景图案样式
const getPatternStyle = computed((): Record<string, string> => {
  if (!bgPattern.value?.pattern) return {};

  const borderColorForPattern = dialogStyle.value.colors.boxBorder.replace(/[\d.]+\)$/, '0.08)');
  const patternWithColor = bgPattern.value.pattern.replace(/VAR_BORDER_COLOR/g, borderColorForPattern);

  let backgroundSize = '20px 20px';
  if (bgPattern.value.id === 'dots') backgroundSize = '16px 16px';
  if (bgPattern.value.id === 'diamonds') backgroundSize = '16px 16px';
  if (bgPattern.value.id === 'stripes') backgroundSize = '28px 28px';

  return {
    backgroundImage: patternWithColor,
    backgroundSize,
  };
});

const boxStyle = computed((): Record<string, string> => {
  const style: Record<string, string> = {
    backgroundColor: isPillShape.value ? 'rgba(255, 255, 255, 0.7)' : dialogStyle.value.colors.boxBackground,
    borderRadius: boxShape.value.borderRadius,
    borderTopWidth: borderWidth.value.width,
    borderLeftWidth: borderWidth.value.width,
    borderRightWidth: borderWidth.value.width,
    borderBottomWidth: borderWidth.value.width,
    borderStyle: 'solid',
    borderColor: dialogStyle.value.colors.boxBorder,
    boxShadow: boxShape.value.shadow,
    ...(isPillShape.value ? { backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)' } : {}),
    ...getPatternStyle.value,
  };
  return style;
});

const outerArrowStyle = computed(() => {
  const isDisabled = props.isFirstDialogue || props.isLastDialogue;
  const iconColor = isDisabled ? `${dialogStyle.value.colors.arrowIcon}66` : dialogStyle.value.colors.arrowIcon;

  if (isMinimalArrow.value) {
    return {
      color: iconColor,
    };
  }

  const bgColor = dialogStyle.value.colors.arrowBackground;
  let borderRadius = '9999px';
  if (arrowShape.value.type === 'square' || arrowShape.value.type === 'inner-square') borderRadius = '6px';
  if (arrowShape.value.type === 'pill') borderRadius = '16px';

  return {
    backgroundColor: bgColor,
    borderRadius,
    color: iconColor,
  };
});

const innerLeftArrowStyle = computed(() => {
  const isDisabled = props.isFirstDialogue;
  const iconColor = isDisabled ? `${dialogStyle.value.colors.arrowIcon}66` : dialogStyle.value.colors.arrowIcon;
  const isRound = arrowShape.value.type === 'inner-round';
  return {
    background: isRound ? dialogStyle.value.colors.arrowBackground : 'transparent',
    color: iconColor,
  };
});

const innerRightArrowStyle = computed(() => {
  const isDisabled = props.isLastDialogue;
  const iconColor = isDisabled ? `${dialogStyle.value.colors.arrowIcon}66` : dialogStyle.value.colors.arrowIcon;
  const isRound = arrowShape.value.type === 'inner-round';
  return {
    background: isRound ? dialogStyle.value.colors.arrowBackground : 'transparent',
    color: iconColor,
  };
});

// 指示器组件
const indicatorComponent = computed((): VNode | null => {
  const { type } = indicatorShape.value;
  const { indicatorColor } = dialogStyle.value.colors;

  if (type === 'none') return null;

  if (type === 'dots') {
    return h(
      'div',
      { class: 'flex gap-1 items-center' },
      [0, 1, 2].map(i =>
        h('span', {
          key: i,
          class: 'w-1.5 h-1.5 rounded-full transition-opacity duration-500',
          style: {
            backgroundColor: indicatorColor,
            opacity: isTyping.value ? (i === 2 ? 1 : 0.4) : 0.6,
            animation: isTyping.value && i === 2 ? 'pulse 1s ease-in-out infinite' : undefined,
          },
        }),
      ),
    );
  }

  if (type === 'diamonds') {
    return h(
      'div',
      { class: 'flex gap-1 items-center' },
      [0, 1, 2].map(i =>
        h('span', {
          key: i,
          class: 'transition-all duration-300',
          style: {
            width: '8px',
            height: '8px',
            backgroundColor: indicatorColor,
            opacity: isTyping.value ? (i === 2 ? 1 : 0.3 + i * 0.15) : 0.5,
            transform: `rotate(45deg) scale(${isTyping.value && i === 2 ? 1.1 : 0.9})`,
            animation: isTyping.value && i === 2 ? 'diamondPulse 1.2s ease-in-out infinite' : undefined,
            display: 'inline-block',
          },
        }),
      ),
    );
  }

  if (type === 'pulse') {
    return h('div', { class: 'relative w-3 h-3' }, [
      h('span', {
        class: 'absolute inset-0 rounded-full',
        style: {
          backgroundColor: indicatorColor,
          opacity: 0.4,
          animation: isTyping.value ? 'ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite' : undefined,
        },
      }),
      h('span', {
        class: 'absolute inset-0 rounded-full',
        style: {
          backgroundColor: indicatorColor,
          animation: isTyping.value ? 'pulse 2s ease-in-out infinite' : undefined,
        },
      }),
    ]);
  }

  if (type === 'arrow') {
    return h(
      'svg',
      {
        class: 'w-4 h-4 transition-transform duration-300',
        style: {
          color: indicatorColor,
          animation: isTyping.value ? 'arrowBounce 0.8s ease-in-out infinite' : undefined,
        },
        fill: 'none',
        stroke: 'currentColor',
        viewBox: '0 0 24 24',
      },
      [
        h('path', {
          'stroke-linecap': 'round',
          'stroke-linejoin': 'round',
          'stroke-width': '2',
          d: 'M9 5l7 7-7 7',
        }),
      ],
    );
  }

  return null;
});

function handlePrev() {
  if (!props.isFirstDialogue) {
    props.onPrev();
  }
}

function handleNext() {
  if (!props.isLastDialogue) {
    props.onNext();
  }
}

function clearTypingTimer() {
  if (typingTimer) {
    clearInterval(typingTimer);
    typingTimer = null;
  }
}

function startTyping() {
  clearTypingTimer();

  if (props.isLoading) {
    displayedText.value = props.text;
    isTyping.value = true;
    return;
  }

  if (!props.text) {
    displayedText.value = '';
    isTyping.value = false;
    return;
  }

  displayedText.value = '';
  isTyping.value = true;

  let index = 0;
  typingTimer = setInterval(() => {
    if (index < props.text.length) {
      displayedText.value = props.text.slice(0, index + 1);
      index++;
    } else {
      isTyping.value = false;
      clearTypingTimer();
      }
  }, TYPING_SPEED);
}

watch(
  () => [props.text, props.dialogKey, props.isLoading],
  () => {
    startTyping();
  },
  { immediate: true },
);

onMounted(() => {
  startTyping();
});

onUnmounted(() => {
  clearTypingTimer();
});

// 编辑/删除功能
const showEditDialog = ref(false);
const editText = ref('');

function handleEdit() {
  if (props.messageId === undefined) return;
  editText.value = props.text;
  showEditDialog.value = true;
}

function handleDelete() {
  if (props.messageId === undefined || !props.onDelete) return;
  if (confirm('确定要删除这条消息吗？')) {
    props.onDelete(props.messageId);
  }
}

function confirmEdit() {
  if (props.messageId === undefined || !props.onEdit) return;
  if (editText.value.trim()) {
    props.onEdit(props.messageId, editText.value.trim());
    showEditDialog.value = false;
  }
}

function cancelEdit() {
  showEditDialog.value = false;
  editText.value = '';
}
</script>

<style scoped>
@keyframes pulse {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.5;
  }
}

@keyframes diamondPulse {
  0%,
  100% {
    opacity: 1;
    transform: rotate(45deg) scale(1);
  }
  50% {
    opacity: 0.6;
    transform: rotate(45deg) scale(0.8);
  }
}

@keyframes ping {
  75%,
  100% {
    transform: scale(2);
    opacity: 0;
  }
}

@keyframes arrowBounce {
  0%,
  100% {
    transform: translateX(0);
  }
  50% {
    transform: translateX(3px);
  }
}
</style>
